# Generated by Django 3.1.2 on 2021-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0002_auto_20210902_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesuarusitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ThesaurusThesuarusitem',
        ),
    ]
