# Generated by Django 3.1.2 on 2021-09-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0003_auto_20210902_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesuarusitem',
            options={},
        ),
    ]
